name: imadjinn
channels:
  - conda-forge
dependencies:
  - python=3.9
  - librosa=0.9.2
  - numpy=1.23.5
  - scipy=1.10.0
  - diffusers=0.12.1
  - gradio=3.16.2
  - matplotlib=3.6.3
  - pip:
    - vosk=0.3.45
    - torch=2.0.0
    - sounddevice=0.4.6
    - opencv-python=4.7.0.72
    - huggingface-hub=0.11.1